service: todo-app-backend

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2

functions:
  tasks:
    handler: handler.tasks
    events:
      - http:
          path: tasks
          method: get
          cors: true
  create:
    handler: handler.tasks.create
    events:
      - http:
          path: tasks/create
          method: post
          cors: true