service: todo-app-backend

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2

functions:
  tasks:
    handler: handler.tasks
    events:
      - http:
          path: tasks
          method: get
          cors: true
  create:
    handler: handler.tasks
    events:
      - http:
          path: tasks/task/create
          method: post
          cors: true
  update:
    handler: handler.tasks
    events:
      - http:
          path: tasks/task/{taskId}
          method: put
          cors: true
  delete:
    handler: handler.tasks
    events:
      - http:
          path: tasks/task/{taskId}
          method: delete
          cors: true